/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_freiheit_gnupg_GnuPGData */

#ifndef _Included_com_freiheit_gnupg_GnuPGData
#define _Included_com_freiheit_gnupg_GnuPGData
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_freiheit_gnupg_GnuPGData
 * Method:    gpgmeDataNewFromMem
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_com_freiheit_gnupg_GnuPGData_gpgmeDataNewFromMem
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_freiheit_gnupg_GnuPGData
 * Method:    gpgmeDataNew
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_freiheit_gnupg_GnuPGData_gpgmeDataNew
  (JNIEnv *, jobject);

/*
 * Class:     com_freiheit_gnupg_GnuPGData
 * Method:    gpgmeDataWrite
 * Signature: (JLjava/io/OutputStream;)V
 */
JNIEXPORT void JNICALL Java_com_freiheit_gnupg_GnuPGData_gpgmeDataWrite
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_freiheit_gnupg_GnuPGData
 * Method:    gpgmeDataRelease
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_freiheit_gnupg_GnuPGData_gpgmeDataRelease
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_freiheit_gnupg_GnuPGData
 * Method:    gpgmeDataRead
 * Signature: (JLjava/io/InputStream;)V
 */
JNIEXPORT void JNICALL Java_com_freiheit_gnupg_GnuPGData_gpgmeDataRead
  (JNIEnv *, jobject, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
