/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_freiheit_gnupg_GnuPGSignature */

#ifndef _Included_com_freiheit_gnupg_GnuPGSignature
#define _Included_com_freiheit_gnupg_GnuPGSignature
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_freiheit_gnupg_GnuPGSignature
 * Method:    gpgmeGetRevoked
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_freiheit_gnupg_GnuPGSignature_gpgmeGetRevoked
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_freiheit_gnupg_GnuPGSignature
 * Method:    gpgmeGetExpired
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_freiheit_gnupg_GnuPGSignature_gpgmeGetExpired
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_freiheit_gnupg_GnuPGSignature
 * Method:    gpgmeGetInvalid
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_freiheit_gnupg_GnuPGSignature_gpgmeGetInvalid
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_freiheit_gnupg_GnuPGSignature
 * Method:    gpgmeGetExportable
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_freiheit_gnupg_GnuPGSignature_gpgmeGetExportable
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_freiheit_gnupg_GnuPGSignature
 * Method:    gpgmeGetKeyID
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_freiheit_gnupg_GnuPGSignature_gpgmeGetKeyID
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_freiheit_gnupg_GnuPGSignature
 * Method:    gpgmeGetUserID
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_freiheit_gnupg_GnuPGSignature_gpgmeGetUserID
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_freiheit_gnupg_GnuPGSignature
 * Method:    gpgmeGetName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_freiheit_gnupg_GnuPGSignature_gpgmeGetName
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_freiheit_gnupg_GnuPGSignature
 * Method:    gpgmeGetEmail
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_freiheit_gnupg_GnuPGSignature_gpgmeGetEmail
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_freiheit_gnupg_GnuPGSignature
 * Method:    gpgmeGetComment
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_freiheit_gnupg_GnuPGSignature_gpgmeGetComment
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_freiheit_gnupg_GnuPGSignature
 * Method:    gpgmeGetNextSignature
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_freiheit_gnupg_GnuPGSignature_gpgmeGetNextSignature
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
