/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_freiheit_gnupg_GnuPGGenkeyResult */

#ifndef _Included_com_freiheit_gnupg_GnuPGGenkeyResult
#define _Included_com_freiheit_gnupg_GnuPGGenkeyResult
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
