#!/bin/bash
# bash is required because we need bash's printf to guarantee a cross-platform
# timestamp format.

set -e
set -x

# make sure we're on a signed tag that matches the version name
versionName=`sed -n 's,.*versionName="\([^"]*\)".*,\1,p' AndroidManifest.xml`
describe=`git describe`
if [ $versionName != $describe ]; then
    echo "WARNING: building $describe, which is not the latest release ($versionName)"
else
    # make a clearer warning above by putting this here
    set +x
    echo ""
    echo ""
    echo "Checking git tag signature for release build:"
    git tag -v $versionName
    echo ""
    echo ""
    set -x
fi


if [ -z $ANDROID_HOME ]; then
    if [ -e ~/.android/bashrc ]; then
        . ~/.android/bashrc
    else
        echo "ANDROID_HOME must be set!"
        exit
    fi
fi

if [ -z $ANDROID_NDK ]; then
    if which ndk-build 2>&1 /dev/null; then
        ANDROID_NDK=`which ndk-build |  sed 's,/ndk-build,,'`
    else
        echo "ANDROID_NDK not set and 'ndk-build' not in PATH"
        exit
    fi
fi

projectroot=`pwd`
projectname=`sed -n 's,.*name="app_name">\(.*\)<.*,\1,p' res/values/strings.xml`

# standardize timezone to reduce build differences
export TZ=UTC
# run the clock at 5% speed, ant requires a moving clock
TIMESTAMP=`printf '@%(%Y-%m-%d %H:%M:%S)T x0.05' \
    $(git log -n1 --format=format:%at)`

git reset --hard
git clean -fdx
git submodule foreach --recursive git reset --hard
git submodule foreach --recursive git clean -fdx
git submodule sync --recursive
git submodule foreach --recursive git submodule sync
git submodule update --init --recursive

make -C external/
$ANDROID_NDK/ndk-build

if [ -e ~/.android/ant.properties ]; then
    cp ~/.android/ant.properties $projectroot/
else
    echo "skipping release ant.properties"
fi

./setup-ant.sh
faketime -f "$TIMESTAMP" ant release

apk=$projectroot/bin/$projectname-$versionName.apk

# mark APK with actual build info, instead of version in manifest
if [ $versionName != $describe ]; then
    debugapk=$projectroot/bin/$projectname-$describe.apk
    mv $apk $debugapk
    apk=$debugapk
fi
if which gpg > /dev/null; then
    if [ -z "`gpg --list-secret-keys`" ]; then
        echo "No GPG secret keys found, not signing APK"
else
        gpg --detach-sign $apk
    fi
else
    echo "gpg not found, not signing APK"
fi
